CONFIG_BOOT_MAX_IMG_SECTORS_AUTO=n
CONFIG_BOOT_MAX_IMG_SECTORS=256
CONFIG_FPROTECT=n
CONFIG_BOOT_WATCHDOG_FEED=n
CONFIG_BOOT_SIGNATURE_TYPE_NONE=y
CONFIG_MCUBOOT_LOG_LEVEL_OFF=y
CONFIG_BOOT_SERIAL_IMG_GRP_HASH=n
CONFIG_MCUBOOT_USE_TLV_ALLOW_LIST=n
CONFIG_MCUBOOT_SERIAL=y
CONFIG_BOOT_SERIAL_CDC_ACM=y
CONFIG_BOOT_SERIAL_ENTRANCE_GPIO=n
CONFIG_BOOT_SERIAL_BOOT_MODE=y
CONFIG_RETAINED_MEM=y
CONFIG_RETENTION=y
CONFIG_RETENTION_BOOT_MODE=y
